version: "3.8"

services:
  database:
    container_name: database
    image: postgres:alpine
    ports:
      - "5432:5432"

  api:
    container_name: api
    build: ./src
    ports:
      - "3000:3000"
    depends_on:
      - database
