version: "3.8"

services:
  database:
    container_name: database
    image: postgres:alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USERNAME
      - PGDATA=/pgdata
      - POSTGRES_PASSWORD=$DB_PASSWORD

  api:
    container_name: api
    build: ./src
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    environment:
      - DB_PORT=$DB_PORT
      - PORT=$PORT
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD