version: "3.8"

services:
  database:
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - PGDATA=/pgdata
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  api:
    env_file: .env
