name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env: 
      - PORT: 3000
      - DB_HOST: database
      - DB_PORT: 5432
      - DB_USERNAME: dmitryshipunov
      - DB_NAME: dmitryshipunov
      - DB_PASSWORD: qwerty
    
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        working-directory: ./src
        run: go mod download

      # - name: Build
      #   working-directory: ./src
      #   run: go build -v .

      - name: Test
        working-directory: ./src
        run: go test ./... -v .

      - name: Build images
        run:  docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build