name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Go to src directory
        working-directory: ./src
        run: go mod download

      - name: Get dependencies
        working-directory: ./src
        run: go mod download

      - name: Build
        working-directory: ./src
        run: go build -v .

      - name: Test
        working-directory: ./src
        run: go test ./... -v .
